// <auto-generated />
using System;
using BlogDesing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogDesing.Migrations
{
    [DbContext(typeof(DbContextAll))]
    [Migration("20220601192600_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogDesing.Models.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("AutorId");

                    b.ToTable("autors");
                });

            modelBuilder.Entity("BlogDesing.Models.AutorToDesing", b =>
                {
                    b.Property<int>("AutorId");

                    b.Property<int>("DesingId");

                    b.HasKey("AutorId", "DesingId");

                    b.HasIndex("DesingId");

                    b.ToTable("AutorToDesing");
                });

            modelBuilder.Entity("BlogDesing.Models.Desing", b =>
                {
                    b.Property<int>("DesingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PhotoOne");

                    b.HasKey("DesingId");

                    b.ToTable("desings");
                });

            modelBuilder.Entity("BlogDesing.Models.AutorToDesing", b =>
                {
                    b.HasOne("BlogDesing.Models.Autor", "Autor")
                        .WithMany("AutorToDesign")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BlogDesing.Models.Desing", "Desing")
                        .WithMany("AutorToDesign")
                        .HasForeignKey("DesingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
